<?php
/** @var \Rezolve\InstantCheckout\Block\ProductListing\View $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->isProductListingEnabled() && $block->isAllowedProductType() && !empty($block->getMerchantId())): ?>
<div class="listing-rezolve-ic-button-wrapper <?= /* @noEscape */ $block->getNameInLayout(); ?>">
    <rezolve-instant-checkout-button
        type="buy"
        merchant="<?= $escaper->escapeHtml($block->getMerchantId()); ?>"
        external_id="<?= /* @noEscape */ $block->getProductId(); ?>"
        class="instant-button <?= $escaper->escapeHtml($block->getListingClasses()); ?>"
        button_style="<?= $escaper->escapeHtml($block->getListingButtonStyle()); ?>"
        image_style="<?= $escaper->escapeHtml($block->getListingImageStyle()); ?>"
        <?= $escaper->escapeHtml($block->getListingCustomWidthStyleValue()); ?>
    ></rezolve-instant-checkout-button>
</div>
<?php endif; ?>
