<?php  /** @var \Rezolve\InstantCheckout\Block\ProductDetail\Button $block */ ?>
<?php if ($block->isProductDetailEnabled() && $block->isAllowedProductType() && !empty($block->getMerchantId())): ?>
<div class="rezolve-ic-button-wrapper <?php echo $block->getNameInLayout(); ?>">
    <rezolve-instant-checkout-button
        type="buy"
        merchant="<?php echo $block->getMerchantId(); ?>"
        external_id="<?php echo $block->getProductId(); ?>"
        class="instant-button <?php echo $block->getClasses(); ?>"
        button_style="<?php echo $block->getProductButtonStyle(); ?>"
        image_style="<?php echo $block->getProductImageStyle(); ?>"
        <?php echo $block->getCustomWidthStyleValue(); ?>
    ></rezolve-instant-checkout-button>
</div>
<?php endif; ?>
