<?php
/** @var \Rezolve\InstantCheckout\Block\ProductDetail\Button $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<?php if ($block->isProductDetailEnabled() && $block->isAllowedProductType() && !empty($block->getMerchantId())): ?>
<rezolve-instant-checkout-button
    type="buy"
    merchant="<?= $escaper->escapeHtml($block->getMerchantId()); ?>"
    external_id="<?= /* @noEscape */ $block->getProductId(); ?>"
    class="instant-button <?= $escaper->escapeHtml($block->getClasses()); ?>"
    button_style="<?= $escaper->escapeHtml($block->getProductButtonStyle()); ?>"
    image_style="<?= $escaper->escapeHtml($block->getProductImageStyle()); ?>"
    <?= /* @noEscape */ $block->getCustomWidthStyleValue(); ?>
></rezolve-instant-checkout-button>
<?php endif; ?>
